# Generated by Django 5.1.1 on 2024-09-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='clientes/%Y/%m/')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hamburgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=500)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='hamburgers/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='SideDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=500)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='SideDishes/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='SweetsTreats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=500)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='SweetsTreats/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacaoClube', models.TextField(max_length=500)),
                ('points', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacaoApp', models.TextField(max_length=500)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
