# Generated by Django 5.1.1 on 2024-09-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descrição_hamburgers_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='crew/%Y/%m/')),
            ],
        ),
    ]
